'use strict'

// API_ERROR
export const SET_APP_ERROR = 'SET_APP_ERROR'
export const UNSET_APP_ERROR = 'UNSET_APP_ERROR'


// SIGN_UP
export const SIGN_UP_START = 'SIGN_UP_START'
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS'
export const SIGN_UP_ERROR = 'SIGN_UP_ERROR'


// LOG_IN
export const LOG_IN_START = 'LOG_IN_START'
export const LOG_IN_SUCCESS = 'LOG_IN_SUCCESS'
export const LOG_IN_ERROR = 'LOG_IN_ERROR'


// LOG_OUT
export const LOG_OUT_START = 'LOG_OUT_START'
export const LOG_OUT_SUCCESS = 'LOG_OUT_SUCCESS'
export const LOG_OUT_ERROR = 'LOG_OUT_ERROR'


// CURRENT_USER
export const FETCH_CURRENT_USER_START = 'FETCH_CURRENT_USER_START'
export const FETCH_CURRENT_USER_SUCCESS = 'FETCH_CURRENT_USER_SUCCESS'
export const FETCH_CURRENT_USER_ERROR = 'FETCH_CURRENT_USER_ERROR'

// CREATE_PROPERTY
export const CREATE_PROPERTY_START = 'CREATE_PROPERTY_START'
export const CREATE_PROPERTY_SUCCESS = 'CREATE_PROPERTY_SUCCESS'
export const CREATE_PROPERTY_ERROR = 'CREATE_PROPERTY_ERROR'
